### ISSUE TITLE
"Agno package not available. Please install with: pip install agno"

### ISSUE THREAD

**Issue by Gwouigwoui** [arsaboo/beets-plexsync#107]
Hi,

When running plex with the plugin active, I get the following error message: "Agno package not available. Please install with: pip install agno".
When checking with pip list, I see I have agno 2.1.0 installed.

How can I solve this?

**Comment by arsaboo** [comment]
It should be fixed now. Try the latest update.

**Comment by Gwouigwoui** [comment]
I updated, but the error is still there, unfortunately.

**Comment by arsaboo** [comment]
Are you using it in venv?

**Comment by arsaboo** [comment]
how are you installing the plugin?

**Comment by Gwouigwoui** [comment]
`pip install --upgrade --force-reinstall --no-deps git+https://github.com/arsaboo/beets-plexsync.git`
And for agno `pip install agno`

I just tried with a new venv, from scratch, and the issue is still there.
